spring.application.name=springBoot

spring.datasource.url=jdbc:postgresql://localhost:5332/db1
spring.datasource.username=ghaida
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true